### ISSUE TITLE
Error:(36, 0) Not valid.

### ISSUE THREAD

**Issue by JeeseC** [onlyloveyd/GankIOWithKotlin#1]
..\GankIOWithKotlin\app\build.gradle
Error:(36, 0) Not valid.

是这行代码出了问题
![qq 20170531162808](https://cloud.githubusercontent.com/assets/18020896/26622809/2aae972e-461e-11e7-9408-7314125f4915.png)

编译的时候，编译不了。

**Comment by onlyloveyd** [comment]
http://blog.csdn.net/poorkick/article/details/72599929
你先按照最后一个问题的修改方式修改一下，马上更新上去
